--SQL문 사용할 것들 메모용
CREATE TABLE users (                                   -- 유저목록
    user_id      VARCHAR2(20) PRIMARY KEY,             -- 학번(학생) 또는 교번(교수)
    name         VARCHAR2(50) NOT NULL,                -- 이름
    password     VARCHAR2(255) NOT NULL,               -- 암호화된 비밀번호
    email        VARCHAR2(100) NOT NULL,               -- 비밀번호 찾기용 이메일
    android_id   VARCHAR2(100),                        -- 최초 로그인 기기 Android ID (학생만 필수)
    role         VARCHAR2(10) NOT NULL,                -- 사용자 구분 ('student' 또는 'professor')
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- 계정 생성 시각
    CONSTRAINT chk_role CHECK (role IN ('student', 'professor'))  -- 역할 제한
);
CREATE TABLE subjects (                              -- 과목별 정보
    subject_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 과목 고유 ID
    name           VARCHAR2(100) NOT NULL,           -- 과목명
    professor_id   VARCHAR2(20),                     -- 담당 교수 ID (users.user_id와 연결됨)
    professor_bssid VARCHAR2(50),  -- BSSID 저장
    CONSTRAINT fk_professor FOREIGN KEY (professor_id) REFERENCES users(user_id)  -- 교수 FK
);
CREATE TABLE enrollments (                       -- 과목별 수강중인 학생목록
    enrollment_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 수강 신청 고유 ID
    student_id     VARCHAR2(20) NOT NULL,        -- 수강 학생 ID
    subject_id     NUMBER NOT NULL,              -- 수강 과목 ID
    CONSTRAINT fk_enroll_student FOREIGN KEY (student_id) REFERENCES users(user_id),   -- 학생 FK
    CONSTRAINT fk_enroll_subject FOREIGN KEY (subject_id) REFERENCES subjects(subject_id) -- 과목 FK
);
CREATE TABLE attendance_records (                      -- 출석리스트
    attendance_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 출석 고유 ID
    student_id          VARCHAR2(20) NOT NULL,         -- 출석한 학생 ID
    subject_id          NUMBER NOT NULL,               -- 과목 ID
    attendance_datetime TIMESTAMP NOT NULL,            -- 출석 처리된 날짜 + 시간(수정하면 안됨)
    status              VARCHAR2(10) NOT NULL,         -- 출석 상태 ('출석', '결석', '지각_조퇴')
    bssid               VARCHAR2(50),                  -- 당시 연결된 Wi-Fi BSSID
    android_id          VARCHAR2(100),                 -- 당시의 안드로이드 ID (위조 확인용)
    last_modified_at    TIMESTAMP,                      -- 출석 수정된 시간
    week_number         NUMBER CONSTRAINT chk_week_range CHECK (week_number BETWEEN 1 AND 16), -- 주차표시
    CONSTRAINT chk_status CHECK (status IN ('출석', '결석', '지각_조퇴')),  -- 상태 제한
    CONSTRAINT fk_attendance_student FOREIGN KEY (student_id) REFERENCES users(user_id),
    CONSTRAINT fk_attendance_subject FOREIGN KEY (subject_id) REFERENCES subjects(subject_id)
);
CREATE TABLE semester_info (
    start_date    DATE NOT NULL  -- 학기 시작일(예: 2025-03-04)
);